#!/usr/bin/env python3
"""Teste automatizado do painel v4 (Playwright + Chrome headless).

Uso:  python3 test_dashboard.py [arquivo_ou_url]
Padrão: .plain/index.html (gerado com  python3 build.py --site --no-encrypt --out .plain/index.html).
Testa a versão SEM criptografia; a versão publicada é a mesma página após o StaticCrypt.
"""
import os, sys, json, pathlib
from playwright.sync_api import sync_playwright

HERE = pathlib.Path(__file__).resolve().parent
target = sys.argv[1] if len(sys.argv) > 1 else str(HERE / '.plain' / 'index.html')
URL = target if '://' in target else pathlib.Path(target).resolve().as_uri()
CHROME = os.environ.get('CHROME', '/usr/bin/google-chrome')
fails = []
def check(cond, msg):
    print(('OK   ' if cond else 'FAIL ') + msg)
    if not cond: fails.append(msg)

with sync_playwright() as p:
    b = p.chromium.launch(executable_path=CHROME if os.path.exists(CHROME) else None, args=['--no-sandbox'])
    ctx = b.new_context(viewport={'width': 1440, 'height': 950}, accept_downloads=True)
    pg = ctx.new_page(); errs = []
    pg.on('pageerror', lambda e: errs.append(str(e)))
    pg.goto(URL, wait_until='load', timeout=180000)
    pg.wait_for_function('window.__dash', timeout=60000); pg.wait_for_timeout(500)
    D = 'window.__dash'
    n = pg.evaluate(D + '.ITEMS.length'); check(n > 1000, f'itens carregados: {n}')
    n0 = pg.evaluate(D + '.CUR.length'); check(0 < n0 <= n, f'lista padrão: {n0} (faixas/áreas comuns e execuções de HOA ocultas)')
    check(pg.evaluate(D + ".S.cat") == 'resid', 'filtro padrão = Residencial (casa/townhouse/condo)')
    top = pg.evaluate(D + ".CUR.slice(0,30).map(r=>r.ty)")
    check(sum(1 for x in top if x in ('Casa','Townhouse','Condo')) >= 20, f'topo da lista é residencial ({top[:8]})')
    check(pg.evaluate(D + '.PR.ret') == 17 and pg.evaluate(D + '.PR.flip') == 25, 'retorno mínimo padrão = 17%, FLIP ≥ 25%')
    check('Orçamento' not in pg.inner_text('body') and 'teto orç' not in pg.inner_text('body'), 'sem orçamento de US$ 150 mil na página')
    check(pg.locator('#tbl tbody tr').count() > 0, 'tabela renderizada')
    heads = pg.evaluate("document.querySelector('#tbl thead').textContent")
    for h in ('Condado', 'Valor de mercado (POV/ARV)', 'POV PO', 'Julgamento', 'NET', 'ROI', 'Veredito', 'Nota', 'Cat.', 'Autor'):
        check(h in heads, f'coluna “{h}”')
    check(pg.evaluate(D + '.ITEMS.filter(r=>r.pov).length') > 50, 'itens com POV PropertyOnion')
    check(pg.evaluate(D + '.ITEMS.filter(r=>r.povAsArv).length') > 20, 'itens com POV como ARV')
    check(pg.evaluate(D + '.ITEMS.filter(r=>r.plat==="PropertyOnion").length') >= 1, 'imóveis só-PropertyOnion')
    check(pg.locator('#fpovc').count()==1 and pg.locator('#hpov').count()==1, 'filtros POV (confiança + só com POV)')
    check(pg.locator('#kstrip > div').count() == 5, 'faixa de KPIs (5 indicadores)')
    check(pg.locator('#kpis > *').count() >= 7, 'blocos de categoria (7)')
    check('JR-LIEN' in pg.inner_text('#jrban'), 'aviso JR-LIEN')
    # seletor de tipo: 9 tipos + Todos
    types = pg.evaluate("[...document.querySelectorAll('#types [data-cat]')].map(b=>b.dataset.cat)")
    check(set(['Lote', 'Terreno', 'Casa', 'Townhouse', 'Condo', 'Mobile', 'Multifamily', 'Comercial', 'Outro']) <= set(types), f'chips de tipo ({len(types)})')
    for t in ('Lote', 'Condo', 'Comercial'):
        pg.click(f'#types [data-cat="{t}"]'); pg.wait_for_timeout(250)
        got = set(pg.evaluate(D + '.CUR.map(r=>r.ty)')); check(got == {t}, f'chip {t} filtra ({len(pg.evaluate(D + ".CUR"))} itens)')
    pg.click('#types [data-cat=""]'); pg.wait_for_timeout(200)
    check(pg.evaluate(D + '.ITEMS.filter(r=>r.ty==="Lote"||r.ty==="Terreno").length') > 200, 'lotes/terrenos incluídos (>200)')
    # vereditos e categorias
    vds = set(pg.evaluate(D + '.ITEMS.map(r=>r.vd)')); check(vds <= {'FLIP', 'CONSIDERAR', 'PASSAR'} and 'FLIP' in vds, f'vereditos {vds}')
    okv = pg.evaluate(D + '.ITEMS.filter(r=>r.roi!=null&&!r.fl.some(f=>f==="avoid"||f==="mtg")).every(r=>r.vd===(r.roi>=0.25?"FLIP":r.roi>=0.17?"CONSIDERAR":"PASSAR"))')
    check(okv, 'veredito: FLIP ≥ 25%, CONSIDERAR 17–25%, PASSAR < 17%')
    check('ABAIXO 17%' in pg.evaluate(D + '.ITEMS.map(r=>r.kat).join()'), 'categoria “ABAIXO 17%”')
    kats = set(pg.evaluate(D + '.ITEMS.map(r=>r.katk)')); check({'viavel', 'jmax', 'abaixo'} <= kats, f'categorias {kats}')
    # fórmula: no lance máximo o ROI é exatamente o mínimo
    bad = pg.evaluate('''(()=>{const d=window.__dash;let bad=[];for(const r of d.ITEMS){ if(r.mb==null||r.mb<=0) continue;
        const p=d.pnl(r,r.mb); if(Math.abs(p.roi-d.PR.ret/100)>0.002) bad.push([r.id,p.roi]); } return bad.slice(0,5);})()''')
    check(not bad, f'ROI no lance máximo = 17% para todos os itens ({bad})')
    dep = pg.evaluate(D + '.ITEMS.filter(r=>r.mb>0).every(r=>Math.abs(r.dep-r.mb*0.05)<1)'); check(dep, 'depósito = 5% do lance máximo')
    # ordenação rápida
    pg.click('#qs [data-sort="net"]'); pg.wait_for_timeout(300)
    nets = pg.evaluate(D + '.CUR.slice(0,30).map(r=>r.net??-1e12)')
    check(nets == sorted(nets, reverse=True), 'ordenar por Maior NET')
    # filtro ROI mínimo (em Mais filtros)
    pg.click('#fmorebtn'); pg.wait_for_timeout(200)
    pg.fill('#mroi', '50'); pg.dispatch_event('#mroi', 'input'); pg.wait_for_timeout(400)
    rois = pg.evaluate(D + '.CUR.map(r=>r.roi)'); check(rois and min(rois) >= 0.5, f'filtro ROI mín. 50% ({len(rois)} itens)')
    pg.click('#blink'); pg.wait_for_timeout(200)
    h = pg.evaluate('location.hash'); check('mroi' in h, 'filtros vão para o link (#f=...)')
    pg.click('#breset'); pg.wait_for_timeout(300)
    check(pg.evaluate(D + '.CUR.length') == n0, 'limpar filtros volta à lista padrão')
    # filtro de água/esgoto
    pg.select_option('#fut', 'known'); pg.wait_for_timeout(300)
    k = pg.evaluate(D + '.CUR.length'); check(k > 0 and pg.evaluate(D + '.CUR.every(r=>r.util)'), f'filtro água/esgoto FDOH ({k})')
    pg.click('#breset'); pg.wait_for_timeout(300)
    # painel de detalhes coerente com a tabela
    pg.click('#qs [data-sort="sc"]'); pg.wait_for_timeout(200)
    rid = pg.evaluate(D + '.CUR.find(r=>r.t==="FC"&&r.ref!=null&&r.net!=null&&r.imgs&&r.imgs.length&&r.sqft>0&&r.yr).id')
    tnet = pg.evaluate(f'{D}.ITEMS.find(r=>r.id==="{rid}").net')
    pg.evaluate(f'{D}.openDrawer("{rid}")'); pg.wait_for_timeout(500)
    dnet = pg.locator('#dplnet').inner_text()
    check(f"{round(tnet):,}".replace(',', '.') in dnet, f'NET do painel = NET da tabela ({dnet} vs {tnet:.0f})')
    check(pg.locator('#drawer a', has_text='Zillow').count() >= 1 and pg.locator('#drawer a', has_text='Realtor').count() >= 1, 'links Zillow e Realtor no painel')
    check(pg.locator('#galmain img').count() == 1, 'galeria: foto exibida')
    pg.click('#gal [data-gt="sv"]'); pg.wait_for_timeout(200)
    check('svembed' in (pg.locator('#galmain iframe').get_attribute('src') or ''), 'galeria: Street View embutido (sem chave)')
    pg.click('#gal [data-gt="sat"]'); pg.wait_for_timeout(200)
    check('t=k' in (pg.locator('#galmain iframe').get_attribute('src') or ''), 'galeria: satélite')
    al = pg.locator('#drawer .alerts li').count(); check(al >= 8, f'alertas de risco ({al})')
    check(pg.locator('#drawer .alerts .st.nv').count() >= 1, 'alertas marcam “não verificado”')
    check(pg.locator('#dland .lv > div').count() >= 9, 'bloco água/esgoto/terreno')
    tiles = pg.evaluate("document.querySelector('#dtiles').textContent")
    for t in ('17% mínimo', '25% alvo', '30% esticado', '70% máx.', 'Julgamento'):
        check(t in tiles, f'escada de lances: {t}')
    check('Depósito no leilão' in pg.inner_text('#ddep'), 'depósito de 5% no painel')
    check(pg.locator('#dstrat > div').count() == 2, 'estratégias FLIP e HOLD/BRRRR')
    pl = pg.evaluate("document.querySelector('#dpl').textContent")
    for t in ('Preço de venda (ARV)', 'Lance vencedor', 'Taxas do clerk', 'Doc stamps na compra', 'Total da aquisição', 'Reforma', 'Contingência', 'Posse', 'Taxa fixa WRA', 'Comissão do corretor vendedor', 'Comissão do corretor comprador', 'Título / escrow', 'Doc stamps na venda', 'Fechamento / diversos', 'Lucro líquido', '/mês'):
        check(t in pl, f'P&L: linha “{t}”')
    check('US$ 399' in pl, 'P&L: WRA US$ 399')
    check(pg.locator('#drepc').count() == 1 and ('RECONSTRUÇÃO' in pg.evaluate("document.querySelector('#drep').textContent")), 'custo de reposição com selo acima/abaixo')
    # clerk fee: 3% of first 500 + 1.5% of rest; formula reproduces BidToFlip example
    ex = pg.evaluate('''(()=>{const d=window.__dash; const r={...d.ITEMS.find(x=>x.id===%r), val:2214600, rep:8000, tax:null, fl:[], t:'FC', ty:'Casa'}; const o={...d.base(r), arv:2214600, rehab:8000, months:4, lien:0}; const p=d.pnl(r,1550220,o); return [Math.round(p.clerk), Math.round(p.docb), Math.round(p.sell.buyc), Math.round(p.sell.title), Math.round(p.sell.docs), p.sell.wra, Math.round(p.sell.list), p.sell.misc, Math.round(p.cont)];})()''' % rid)
    check(ex[:6] == [23261, 10852, 55365, 33219, 15502, 399], f'deduções no formato BidToFlip (clerk, doc stamps, comprador, título, doc stamps venda, WRA) {ex[:6]}')
    check(ex[6] == 55365 and ex[7] == 1500 and ex[8] == 800, f'padrões realistas: vendedor 2,5%, fechamento US$ 1.500, contingência 10% {ex[6:]}')
    defs = pg.evaluate(D + '.PDEF'); check(defs['months'] == 6 and defs['monthsLot'] == 4 and defs['hins'] == 1 and defs['hutil'] == 350 and defs['rhbUnk'] == 35000, 'padrões: posse 6 meses (lote 4), seguro 1%, US$ 350/mês, reforma desconhecida US$ 35 mil')
    # every P&L line editable, live recalculation
    n_in = pg.locator('#dpl .pin').count(); check(n_in >= 14, f'P&L editável ({n_in} campos)')
    before = pg.locator('#dplnet').inner_text()
    pg.fill('#dpl [data-pk="list"]', '6'); pg.wait_for_timeout(200)
    after = pg.locator('#dplnet').inner_text(); check(after != before, f'editar comissão recalcula ao vivo ({before} → {after})')
    pg.fill('#dpl [data-ok="months"]', '9'); pg.wait_for_timeout(200)
    check(pg.locator('#w-months').input_value() == '9', 'meses editados no P&L sincronizam com o simulador')
    pg.click('#w-reset'); pg.wait_for_timeout(200)
    check(pg.locator('#dplnet').inner_text() == before, 'desfazer edições do imóvel')
    pg.fill('#dpl [data-pk="hutil"]', '400'); pg.wait_for_timeout(150); pg.click('#plsave'); pg.wait_for_timeout(300)
    check((json.loads(pg.evaluate("localStorage.getItem('leilao_premissas_v4')") or '{}')).get('hutil') == 400, 'salvar custos como padrão (localStorage)')
    pg.evaluate(f'{D}.openDrawer("{rid}")'); pg.wait_for_timeout(300); pg.click('#pldef'); pg.wait_for_timeout(300)
    check(pg.evaluate("localStorage.getItem('leilao_premissas_v4')") is None and pg.evaluate(D + '.PR.hutil') == 350, 'voltar aos padrões originais')
    pg.evaluate(f'{D}.openDrawer("{rid}")'); pg.wait_for_timeout(300)
    # what-if exactly like BidToFlip: every line follows bid / ARV / rehab / months live
    row = '''(t=>{const tr=[...document.querySelectorAll('#dpl tr')].find(x=>x.cells[0]&&x.cells[0].textContent.startsWith(t));return tr?tr.cells[1].textContent:null;})'''
    snap = lambda: pg.evaluate('''()=>{const g=%s;return {clerk:g('Taxas do clerk'),docb:g('Doc stamps na compra'),list:g('Comissão do corretor vendedor'),hold:g('Posse'),net:document.querySelector('#dplnet').textContent,lad:document.querySelector('#dtiles').textContent,rep:(document.querySelector('#drep')||{}).textContent,dep:document.querySelector('#ddep').textContent,wsr:document.querySelector('#wsr').textContent,hdr:document.querySelector('#dnet').textContent};}''' % row)
    s0 = snap()
    pg.fill('#w-bid', '123500'); pg.wait_for_timeout(150); s1 = snap()
    check(s1['clerk'] != s0['clerk'] and s1['docb'] != s0['docb'] and s1['net'] != s0['net'] and s1['dep'] != s0['dep'] and s1['hdr'] != s0['hdr'] and 'US$ 123.500' in s1['wsr'], 'lance digitado: clerk, doc stamps, lucro, ROI, depósito e cabeçalho ao vivo')
    check(s1['rep'] != s0['rep'] or not s0['rep'], 'lance digitado: custo de reposição ao vivo')
    check(pg.locator('#w-sl').input_value() == '123500', 'campo do lance sincroniza com o slider')
    pg.locator('#w-sl').evaluate("e=>{e.value=80000;e.dispatchEvent(new Event('input',{bubbles:true}))}"); pg.wait_for_timeout(150); s2 = snap()
    check(pg.locator('#w-bid').input_value() == '80000' and s2['clerk'] != s1['clerk'] and s2['net'] != s1['net'], 'slider do lance: campo e linhas ao vivo')
    pg.fill('#w-arv', '450000'); pg.wait_for_timeout(150); s3 = snap()
    check(s3['list'] != s2['list'] and s3['lad'] != s2['lad'] and s3['net'] != s2['net'] and s3['hold'] != s2['hold'], 'ARV: comissões, posse (seguro/imposto), lucro e escada ao vivo')
    pg.fill('#w-rehab', '60000'); pg.wait_for_timeout(150); s4 = snap()
    check(s4['lad'] != s3['lad'] and s4['net'] != s3['net'] and pg.locator('#dpl [data-ok="rehab"]').input_value() == '60000', 'reforma: escada, lucro e linha do P&L ao vivo')
    pg.fill('#w-months', '10'); pg.wait_for_timeout(150); s5 = snap()
    check(s5['hold'] != s4['hold'] and s5['lad'] != s4['lad'], 'meses de posse: posse e escada ao vivo')
    pg.click('#w-reset'); pg.wait_for_timeout(150)
    check(pg.locator('#dcomps, #drawer .sec h3:has-text("comparáveis")').count() >= 1, 'bloco de comps')
    check(pg.locator('#dhist').count() == 1, 'bloco de histórico de leilões')
    mb = pg.evaluate(f'{D}.ITEMS.find(r=>r.id==="{rid}").mb')
    pg.fill('#w-bid', str(round(mb))); pg.dispatch_event('#w-bid', 'input'); pg.wait_for_timeout(200)
    t = pg.locator('#dplnet').inner_text()
    check(any(x in t for x in ('17,0% ROI', '16,9% ROI', '17,1% ROI')), 'simulador: no lance máximo ROI ≈ 17% (' + t + ')')
    pg.click('#w-reset'); pg.wait_for_timeout(200)
    check(f"{round(tnet):,}".replace(',', '.') in pg.locator('#dplnet').inner_text(), 'Reset volta ao valor da tabela')
    pg.click('[data-trk="interessa"]'); pg.wait_for_timeout(100)
    check('interessa' in (pg.evaluate("localStorage.getItem('leilao_tracker_v1')") or ''), 'flip tracker salvo no aparelho')
    pg.click('#dclose'); pg.wait_for_timeout(200)
    # lote com utilidades
    lid = pg.evaluate(D + '.ITEMS.find(r=>(r.ty==="Lote"||r.ty==="Terreno")&&r.util)?.id')
    check(bool(lid), 'existe lote com dado de água/esgoto')
    if lid:
        pg.evaluate(f'{D}.openDrawer("{lid}")'); pg.wait_for_timeout(400)
        check('Terreno' in pg.evaluate("document.querySelector('#dland h3').textContent"), 'painel do lote mostra bloco de terreno')
        pg.click('#dclose'); pg.wait_for_timeout(200)
    # favoritos e cores
    pg.locator('#tbl [data-star]').first.click(); pg.wait_for_timeout(100)
    check(len(json.loads(pg.evaluate("localStorage.getItem('leilao_fav_v1')") or '[]')) == 1, 'favorito salvo (★)')
    pg.locator('#tbl [data-flag]').first.click(); pg.wait_for_timeout(100)
    check(len(json.loads(pg.evaluate("localStorage.getItem('leilao_flags_v1')") or '{}')) == 1, 'cor marcada salva')
    # premissas
    mb10 = pg.evaluate(f'{D}.ITEMS.find(r=>r.id==="{rid}").mb')
    pg.evaluate(f'{D}.applyPrem({{...{D}.PR, ret:25}})'); pg.wait_for_timeout(300)
    mb20 = pg.evaluate(f'{D}.ITEMS.find(r=>r.id==="{rid}").mb')
    check(mb20 < mb10, f'premissa retorno 25% reduz lance máx. ({mb10:.0f} → {mb20:.0f})')
    check(pg.evaluate("localStorage.getItem('leilao_premissas_v4')") is not None, 'premissas salvas (v4)')
    pg.evaluate(f'{D}.applyPrem({{...{D}.PDEF}})'); pg.wait_for_timeout(300)
    check(pg.evaluate("localStorage.getItem('leilao_premissas_v4')") is None, 'padrões restaurados')
    # CSV
    with pg.expect_download() as dl: pg.click('#bcsv')
    lines = open(dl.value.path(), encoding='utf-8-sig').read().splitlines()
    check(len(lines) >= n0 + 1 and 'zillow' in lines[0] and 'deposito' in lines[0], f'CSV exportado ({len(lines)-1} linhas)')
    # outras visões
    pg.click('#tabs [data-v="cards"]'); pg.wait_for_timeout(300); check(pg.locator('#grid .card').count() > 0, 'cards')
    pg.click('#tabs [data-v="fav"]'); pg.wait_for_timeout(300); check(pg.locator('#grid .card').count() == 1, 'aba Favoritos')
    pg.click('#tabs [data-v="intel"]'); pg.wait_for_timeout(300); check(pg.locator('#v-intel tbody tr').count() > 20, 'inteligência por condado')
    check(pg.locator('#v-intel .heat [data-heat]').count() == 9, 'mapa de calor valor × desconto')
    pg.click('#tabs [data-v="res"]'); pg.wait_for_timeout(300); check(pg.locator('#v-res tbody tr').count() > 20, 'resultados de leilões passados')
    pg.click('#tabs [data-v="cal"]'); pg.wait_for_timeout(300)
    check(pg.locator('#v-cal .calrow').count() > 5, f'calendário ({pg.locator("#v-cal .calrow").count()} dias)')
    check(pg.locator('#v-cal .super').count() >= 1, 'calendário marca super dias')
    pg.click('#tabs [data-v="day"]'); pg.wait_for_timeout(300)
    check(pg.locator('#daytbl tbody tr').count() == 1, 'lista do dia do leilão (favorito)')
    with pg.expect_download() as dl: pg.click('#daycsv')
    dl_lines = open(dl.value.path(), encoding='utf-8-sig').read().splitlines()
    check(len(dl_lines) == 2 and 'deposito_usd' in dl_lines[0] and 'processo' in dl_lines[0], 'CSV do dia (lance máx., depósito, processo)')
    pg.click('#tabs [data-v="map"]'); pg.wait_for_timeout(3000)
    check(pg.locator('#map .leaflet-interactive').count() > 0, 'mapa com pontos')
    check(pg.locator('.mapleg').count()>=1, 'legenda do mapa')
    z = pg.evaluate(f'{D}.zillowUrl({D}.ITEMS[0])'); check(z.startswith('https://www.zillow.com/homes/') and z.endswith('_rb/'), 'formato do link Zillow')
    check('US$' in pg.inner_text('#kpis') + pg.inner_text('#sumline') and 'R$' not in pg.inner_text('body'), 'moeda: só US$')
    check(not errs, f'sem erros de JavaScript {errs[:3]}')
    # surviving-lien + Meus candidatos
    surv_n = pg.evaluate(D + ".ITEMS.filter(r=>r.fl.includes('surv')||r.survAmt).length")
    check(surv_n >= 1, f'imóveis com alerta hipoteca pode sobreviver: {surv_n}')
    check(pg.evaluate(D + ".ITEMS.filter(r=>r.fl.includes('surv')).every(r=>!r.clean)"), 'surv fora de Negócios limpos')
    check('Hipoteca pode sobreviver' in pg.evaluate("window.__dash.FL.surv.l"), 'selo FL.surv')
    check(pg.locator('#tabs [data-v="cand"]').count()==1, 'aba Meus candidatos')
    # add candidato from first list row
    rid = pg.evaluate(D + ".CUR[0].id")
    pg.evaluate(f"window.__dash.candAdd('{rid}')")
    pg.click('#tabs [data-v="cand"]'); pg.wait_for_timeout(400)
    check(pg.evaluate(D + '.view')=='cand', 'view candidatos')
    check(pg.locator('.ccard').count() >= 1, 'card de candidato renderizado')
    check(pg.locator('.cchk input[type=checkbox]').count() >= 4, 'checklist no candidato')
    check('Lance máx.' in pg.inner_text('.ccard'), 'mostra lance máx. 17%')
    pg.locator('.cchk input[type=checkbox]').first.check(); pg.wait_for_timeout(200)
    prog = pg.inner_text('.cprog')
    check('1/5' in prog or '2/5' in prog, f'progresso checklist atualiza ({prog[:40]})')
    pg.evaluate("window.__dash.candRem(Object.keys(window.__dash.CAND)[0])")
    pg.wait_for_timeout(200)
    # bid-fill: some former nobid now have ref
    filled = pg.evaluate(D + ".ITEMS.filter(r=>r.plat==='PropertyOnion' && r.ref!=null && !r.nobid).length")
    still = pg.evaluate(D + ".ITEMS.filter(r=>r.nobid).length")
    check(filled >= 1, f'PO-only com FJ/OB preenchido: {filled} (ainda nobid={still})')
    pg.click('#tabs [data-v="table"]'); pg.wait_for_timeout(200)
    xbad = pg.evaluate("""(()=>{const d=window.__dash; const bad=[];
      for(const r of d.ITEMS){ if(r.xbid==null||r.roi==null) continue;
        const p=d.pnl(r,r.xbid); if(Math.abs((p.roi||0)-r.roi)>0.01) bad.push(r.id); }
      return bad.slice(0,3);})()""")
    check(not xbad, f'ROI da capa = P&L no lance realista ({xbad})')
    td = pg.evaluate("""(()=>{const d=window.__dash; const rows=d.ITEMS.filter(r=>r.t==="TD"&&r.mb>1000&&r.ref!=null&&r.ref<r.mb*0.2&&r.xbid!=null);
      const low=rows.filter(r=>r.xbid+1<r.ref || r.xbid+1<0.55*r.mb-1);
      const gap=rows.filter(r=>r.roi0!=null && r.roi!=null && r.roi0>r.roi+0.5);
      return {n:rows.length, low:low.length, gap:gap.length};})()""")
    check(td['n']>20 and td['low']==0 and td['gap']>5, f'tax deed no lance realista {td}')
    sus = pg.evaluate("""(()=>{const d=window.__dash; const s=d.ITEMS.filter(r=>r.suspect);
      const bad=s.filter(r=>r.risk==="baixo" || (r.sc!=null && r.sc>60) || (r.val0!=null && r.val>r.val0+1));
      return {n:s.length, bad:bad.length};})()""")
    check(sus['n']>=1 and sus['bad']==0, f'valor suspeito {sus}')
    check(pg.evaluate('window.__dash.ITEMS.every(r=>!r.titleNv || r.risk!=="baixo")'), 'título não verificado não é risco baixo')
    check(pg.evaluate('window.__dash.ITEMS.filter(r=>r.hist&&r.hist.length).every(r=>r.fl.includes("rebid")&&r.risk!=="baixo")'), 'leilão anterior com flag')
    check(pg.locator('#bgloss').count()==1, 'botão Glossário')
    pg.fill('#q', 'zzzz-sem-match'); pg.dispatch_event('#q', 'input'); pg.wait_for_timeout(400)
    check('Filtros ativos' in pg.inner_text('#fnotice'), 'aviso de filtros ativos')
    pg.click('#fnotice-clear'); pg.wait_for_timeout(400)
    check('Filtros ativos' not in (pg.locator('#fnotice').inner_text() or ''), 'limpar some com o aviso')
    # celular 390px
    m = b.new_context(viewport={'width': 390, 'height': 844}, device_scale_factor=2, is_mobile=True, has_touch=True)
    mp = m.new_page(); merr = []; mp.on('pageerror', lambda e: merr.append(str(e)))
    mp.goto(URL, wait_until='load', timeout=180000); mp.wait_for_function('window.__dash', timeout=60000); mp.wait_for_timeout(500)
    check(mp.evaluate('document.documentElement.scrollWidth') <= 392, 'celular: sem rolagem horizontal')
    check(mp.locator('#grid .card').count() > 0, 'celular abre em cards')
    check(mp.locator('#tbl tbody tr').count() == 0 or not mp.locator('#v-table').is_visible(), 'celular: tabela larga oculta (cards no lugar)')
    check(mp.evaluate("getComputedStyle(document.querySelector('#typesbar')).position") == 'sticky', 'celular: chips de tipo fixos no topo (sticky)')
    check(mp.evaluate("getComputedStyle(document.querySelector('#ftoggle')).position") == 'fixed', 'celular: botão flutuante de filtros')
    overlap = mp.evaluate("(()=>{const a=document.querySelector('#kstrip').getBoundingClientRect(); const b=document.querySelector('#ftoggle').getBoundingClientRect(); return !(b.right<a.left||b.left>a.right||b.bottom<a.top||b.top>a.bottom);})()")
    check(overlap==False, 'celular: botão de filtros não cobre os KPIs')
    clipped = mp.evaluate("[...document.querySelectorAll('#types .chip')].filter(e=>e.scrollWidth>e.clientWidth+2).length")
    check(clipped==0, f'celular: chips de tipo sem corte ({clipped})')
    check(not mp.locator('#filters .fgrid').is_visible(), 'celular: filtros recolhidos')
    mp.click('#ftoggle'); mp.wait_for_timeout(300)
    sheet = mp.evaluate("(()=>{const r=document.querySelector('#filters').getBoundingClientRect();return [getComputedStyle(document.querySelector('#filters')).position, Math.round(r.bottom), Math.round(r.width)]})()")
    check(sheet[0] == 'fixed' and sheet[1] >= 840 and sheet[2] >= 388 and mp.locator('#filters .fgrid').is_visible(), f'celular: filtros em painel inferior (bottom sheet) {sheet}')
    check('Ver' in mp.inner_text('#ftoggle'), 'celular: botão “Ver N imóveis” no painel de filtros')
    mp.click('#ftoggle'); mp.wait_for_timeout(300)
    check(not mp.locator('#filters .fgrid').is_visible(), 'celular: painel de filtros fecha')
    small = mp.evaluate("[...document.querySelectorAll('#types .chip, #ftoggle, #grid .card [data-star]')].filter(e=>e.offsetParent&&e.getBoundingClientRect().height<36).length")
    check(small == 0, f'celular: alvos de toque ≥ 36 px ({small} pequenos)')
    rid = mp.evaluate("window.__dash.CUR.find(r=>r.imgs&&r.imgs.length>1)?.id")
    if rid:
        mp.evaluate(f"window.__dash.openDrawer('{rid}')")
    else:
        mp.locator('#grid .card').first.click()
    mp.wait_for_timeout(500)
    check(mp.evaluate("document.querySelector('#drawer').getBoundingClientRect().width") >= 380, 'celular: painel em tela cheia')
    if rid:
        src0 = mp.get_attribute('#galimg', 'src')
        box = mp.locator('#galmain').bounding_box()
        mp.evaluate('''(()=>{const el=document.querySelector('#galmain');const mk=(t,x)=>new TouchEvent(t,{bubbles:true,touches:t==='touchend'?[]:[new Touch({identifier:1,target:el,clientX:x,clientY:200})],changedTouches:[new Touch({identifier:1,target:el,clientX:x,clientY:200})]});el.dispatchEvent(mk('touchstart',300));el.dispatchEvent(mk('touchend',120));})()''')
        mp.wait_for_timeout(300)
        check(mp.get_attribute('#galimg', 'src') != src0 and '2 /' in mp.inner_text('#galmain'), 'celular: galeria troca foto com swipe')
    check(not mp.locator('#ftoggle').is_visible(), 'celular: botão de filtros some com o painel aberto')
    check(mp.evaluate("document.querySelector('#drawer').scrollWidth <= document.querySelector('#drawer').clientWidth + 2"), 'celular: painel sem rolagem horizontal')
    check(not merr, 'celular: sem erros JS')
    b.close()
print('\n' + ('TODOS OS TESTES OK' if not fails else f'{len(fails)} FALHA(S)'))
sys.exit(1 if fails else 0)
